image: python:3.13-bookworm

default:
  before_script:
    - python -m pip install "poetry>=2.1.0"
    - python -m pip install "poetry-dynamic-versioning>=1.1.0,<2.0.0"
    # - python -m pip install "poetry-plugin-export==1.9.0"

    # add wegcpypi-server
    - echo "[global]" > /etc/pip.conf
    - echo "extra-index-url = https://wegcpypi.uni-graz.at/simple" >> /etc/pip.conf

stages:
  - test
  - publish

test:
  stage: test
  script:
    - poetry install --no-interaction
    - poetry run pytest

publish:package:
  stage: publish
  script:
    - poetry config repositories.wegc $PYPI_SERVER
    - poetry config http-basic.wegc $PYPI_USERNAME $PYPI_PASSWORD
    - poetry build
    - poetry publish -r wegc
  only:
    - tags
