# Template for gridded data TEA indicators; for details and available options see CFG-PARAMS-doc.md
common_params:
  input_data: &DATA
    dataset: ERA5
  GeoRegion: &GR
    region: "NO"
    agr: "NO"
    grg_grid_spacing: 0.25
    land_frac_min: 0.25
  parameter: &PARAM
    parameter: Tx
    precip: false
    threshold_type: perc
    threshold: 99
    unit: degC
    low_extreme: false
  time_params: &TIME
    start: 1961
    end: 2025
    period: annual
    ref_period: 1961-1990
    cc_period: 2011-2025
  paths: &PATHS
    input_data_path: &inputpath /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/EUR/daily/
    hourly_data_path: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/EUR/daily/
    statpath: &statpath /home/wegnet/results/static/
    maskpath: *statpath
    mask_sub: masks/
    outpath: /home/wegnet/results/TEA_indicators_test/
  general: &GENERAL
    use_dask: false

create_region_masks:
  <<: *GR
  <<: *PARAM
  <<: *DATA
  <<: *PATHS
  <<: *TIME
  <<: *GENERAL
  gr_type: polygon
  sw_corner: null
  ne_corner: null
  center: null
  we_len: null
  ns_len: null
  target_sys: 4326
  shpfile: /data/arsclisys/backup/clim-hydro/TEA-Indicators/shapefiles/shapes_europe/CNTR_RG_01M_2020_4326.shp.zip
  orofile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/EUR/ERA5_orography.nc
  lsmfile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/ERA5_LSM.nc
  outpath: /data/arsclisys/normal/clim-hydro/TEA-Indicators/masks/

calc_TEA:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  <<: *GENERAL
  recalc_threshold: false
  recalc_daily: false
  hourly: false
  decadal: true
  recalc_decadal: true
  spreads: true
  annual_spreads: true
  decadal_only: false