common_params:
  GeoRegion: &GR
    region: SEA
  parameter: &PARAM
    parameter: Tx
    precip: false
    threshold: 99
    threshold_type: perc
    unit: degC
    low_extreme: false
    significant_digits: 3
  time_params: &TIME
    start: 1961
    end: 2024
    period: annual
    ref_period: 1961-1990
    cc_period: 2010-2024
  dataset: &DATA
    dataset: SPARTACUS
  paths: &PATHS
    data_path: /data/arsclisys/normal/clim-hydro/TEA-Indicators/SPARTACUS/
    statpath: &statpath /home/wegnet/results/static/
    maskpath: *statpath
    mask_sub: masks/

calc_TEA:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  outpath: /home/wegnet/results/TEA_indicators_test/
  recalc_threshold: false
  recalc_daily: true
  decadal: true
  spreads: false
  decadal_only: false
  recalc_decadal: true

create_region_masks:
  <<: *GR
  <<: *PATHS
  <<: *DATA
  <<: *PARAM
  <<: *TIME
  # use UTM33N for SPARTACUS, because it has been regridded to WEGN grid
  target_sys: 32633
  gr_type: polygon
