common_params:
  gui: &GUI
    gui: false
  GeoRegion: &GR
    region: EUR
    gr_type: polygon
    sw_corner: null
    ne_corner: null
    center: null
    we_len: null
    ns_len: null
  parameter: &PARAM
    parameter: Tx
    precip: false
    threshold: 99
    threshold_type: perc
    unit: degC
    low_extreme: false
  time_params: &TIME
    start: 1961
    end: 2022
    period: WAS
  dataset: &DATA
    dataset: SPARTACUS
  paths: &PATHS
    maskpath: /data/arsclisys/normal/clim-hydro/TEA-Indicators/masks/
    statpath: /home/wegnet/results/static/
#    statpath: /data/arsclisys/normal/clim-hydro/TEA-Indicators/static/
    tmppath: /home/wegnet/results/TEA_indicators_hst/tmp/

regrid_SPARTACUS_to_WEGNext:
  <<: *PARAM
  inpath: /data/users/hst/TEA-clean/SPARTACUS/
  target_grid: wegn
  orography: false
  orofile: /data/reloclim/backup/ZAMG_INCA/data/original/INCA_orog_corrected_y_dim.nc
  wegnfile: /data/users/hst/cdrDPS/wegnet/WN_L2_DD_v7_UTM_TF1_UTC_2020-08.nc
  outpath: /home/wegnet/results/TEA_indicators_hst/

create_region_masks:
  <<: *GUI
  <<: *GR
  subreg: custom
  target_sys: 4326
  target_ds: ERA5
  xy_name: lon,lat
  shpfile: /data/reloclim/backup/GEO/shapefiles/OEKS15/good/AUSTRIA.shp
  testfile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/ERA5_1961.nc
  orofile: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/ERA5_orography.nc
  lsmfile: /data/users/hst/cdrDPS/ERA5/ERA5_LSM.nc
  outpath: /home/wegnet/results/TEA_indicators_hst/

create_static_files:
  <<: *GR
  <<: *TIME
  <<: *PARAM
  <<: *DATA
  <<: *PATHS
  season_length: 366
  smoothing: 0
  inpath: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/
  outpath: /home/wegnet/results/TEA_indicators_hst/static/

calc_TEA:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  inpath: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/
  outpath: /home/wegnet/results/TEA_indicators_hst/
  recalc_daily: false
  decadal: true
  spreads: false
  decadal_only: true
  recalc_decadal: false

calc_station_TEA:
  <<: *GUI
  <<: *TIME
  <<: *PARAM
  station: Graz
  inpath: /data/arsclisys/normal/clim-hydro/TEA-Indicators/ERA5/
  outpath: /home/wegnet/results/TEA_indicators_hst/

calc_amplification_factors:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  supplementary: true
  inpath: /home/wegnet/results/TEA_indicators_hst/dec_indicator_variables/
  # inpath: /data/users/hst/TEA-clean/TEA/dec_indicator_variables/
  outpath: /home/wegnet/results/TEA_indicators_hst/

calc_AGR_vars:
  <<: *GR
  <<: *PARAM
  <<: *TIME
  <<: *DATA
  <<: *PATHS
  inpath: /home/wegnet/results/TEA_indicators_hst/dec_indicator_variables/
#  inpath: /data/users/hst/TEA-clean/TEA/dec_indicator_variables/
  # outpath: /data/users/hst/TEA-clean/TEA/
  outpath: /home/wegnet/results/TEA_indicators_hst/
  agr: EUR
  spreads: true
