#!/usr/bin/env python3
"""Aggregate daily SPARTACUS precipitation files to monthly sums."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import xarray as xr


DEFAULT_INPUT_DIR = Path("/data/arsclisys/normal/SPARTACUS/reproj_StatAT/v2.1")
DEFAULT_OUTPUT = Path(
    "/data/arsclisys/normal/clim-hydro/TEA-Indicators/results/heatwave_paper/"
    "SPARTACUS_RR_monthly/SPARTACUS2-MONTHLY_RR_1961-2026.nc"
)
FILE_PATTERN = "SPARTACUS2-DAILY_RR_*.nc"


def _last_complete_month(times: pd.DatetimeIndex) -> pd.Period:
    """Return the latest calendar month for which every date is available."""
    if times.empty:
        raise ValueError("Input files contain no timestamps")

    if times.has_duplicates:
        raise ValueError("Input files contain duplicate timestamps")

    periods = times.to_period("M")
    counts = pd.Series(1, index=periods).groupby(level=0).sum()
    complete = [period for period, count in counts.items() if count == period.days_in_month]
    if not complete:
        raise ValueError("Input files contain no complete calendar month")
    return max(complete)


def aggregate_monthly(input_dir: Path, output: Path, overwrite: bool = False) -> None:
    """Aggregate all matching daily RR files in *input_dir* into *output*."""
    files = sorted(input_dir.glob(FILE_PATTERN))
    if not files:
        raise FileNotFoundError(f"No files matching {FILE_PATTERN!r} in {input_dir}")
    if output.exists() and not overwrite:
        raise FileExistsError(f"Output exists; use --overwrite to replace it: {output}")

    ds = xr.open_mfdataset(
        files,
        combine="by_coords",
        data_vars="minimal",
        coords="minimal",
        compat="equals",
        chunks={"time": 31},
    )
    try:
        if "RR" not in ds or "time" not in ds.coords:
            raise ValueError("Input files must contain an RR variable and time coordinate")

        times = pd.DatetimeIndex(ds.time.values)
        last_complete = _last_complete_month(times)
        cutoff = last_complete.end_time.normalize()
        ds = ds.sel(time=slice(None, cutoff.to_datetime64()))

        # Materialize the reduced array before writing. This avoids leaving a
        # large multi-file dask graph for the NetCDF backend to evaluate.
        monthly_rr = (
            ds["RR"].resample(time="MS").sum(dim="time", min_count=1).compute()
        )
        result = monthly_rr.to_dataset(name="RR")

        # Keep static grid-mapping information that is not attached as a coordinate.
        for name in ds.data_vars:
            if name != "RR":
                result[name] = ds[name]

        result.attrs = dict(ds.attrs)
        result.attrs["freq"] = "1MS"
        result.attrs["history"] = (
            f"Monthly sums through {last_complete} generated by "
            "aggregate_monthly_RR.py; " + result.attrs.get("history", "")
        )
        result["RR"].attrs = dict(ds["RR"].attrs)
        result["RR"].attrs["cell_method"] = "time: sum"
        result["RR"].attrs["long_name"] = "monthly precipitation sum"
        for key in ("units", "calendar"):
            if key in ds["time"].encoding:
                result["time"].encoding[key] = ds["time"].encoding[key]

        output.parent.mkdir(parents=True, exist_ok=True)
        encoding = {
            "RR": {
                "zlib": True,
                "complevel": 1,
                "dtype": "float32",
                "_FillValue": -9999.0,
            }
        }
        result.to_netcdf(output, format="NETCDF4", encoding=encoding)
        print(f"Aggregated {len(files)} files through {last_complete}: {output}")
    finally:
        ds.close()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, default=DEFAULT_INPUT_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    aggregate_monthly(args.input_dir, args.output, overwrite=args.overwrite)


if __name__ == "__main__":
    main()
